{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.12.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.3.jar",
          "url": "builder-8.12.3.jar",
          "size": 15786422,
          "sha512": "73e4acda722ec485b59e7c0142ced3577f6480fd18bc0426a96c9aeb0069f4012d32bf9ca1b1014cae26f1be0e323a766937ffbe53cfe5807151eea2e462cb0e",
          "sha256": "a9ef76c9da931be9889a80afeec67423409869537df2b06d555d069301f37304",
          "sha1": "7e475b41b820f3f0bd49452034d272d0277d27b3",
          "md5": "07d9b94636da21002ce92616b475966c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.3"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.3.jar",
          "url": "builder-8.12.3.jar",
          "size": 15786422,
          "sha512": "73e4acda722ec485b59e7c0142ced3577f6480fd18bc0426a96c9aeb0069f4012d32bf9ca1b1014cae26f1be0e323a766937ffbe53cfe5807151eea2e462cb0e",
          "sha256": "a9ef76c9da931be9889a80afeec67423409869537df2b06d555d069301f37304",
          "sha1": "7e475b41b820f3f0bd49452034d272d0277d27b3",
          "md5": "07d9b94636da21002ce92616b475966c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.3-javadoc.jar",
          "url": "builder-8.12.3-javadoc.jar",
          "size": 341755,
          "sha512": "d5cdd3c3df62a28724ebe7c3290ff1138922e9fa44f26d6d95cbd0887261a168b665b472eba7bd818767307e3d5b31666a1ea15743d26f23a719e6861ecedd0c",
          "sha256": "794090d050bf86685ca86d4f01f57f8b7d3df9180a2773b50c1ebbd976b153f4",
          "sha1": "53cc1b2e6503c7b6741f3496ae77d032b107116d",
          "md5": "3436264d4b10951ecb72698dd8e4af05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.3-sources.jar",
          "url": "builder-8.12.3-sources.jar",
          "size": 283760,
          "sha512": "d7b47a70c638f9d06ea959a4f00ec54afd8cf32381f10da0707b8e1c7b9239c50b1d5951d80d91e21d5305e7873a8a3d974ef70c70aa88ca88079a993151aeeb",
          "sha256": "12909cb40161b16f312f27c46e20d17ea98565f4d24d796f8a409248e93bc9d5",
          "sha1": "782ba7c70d49cc4b0bd84d011dc170d0261c1b9a",
          "md5": "f8657b8062c5cc65f907db62aa915358"
        }
      ]
    }
  ]
}
